### PR TITLE
Update status.sh

### PR DESCRIPTION
**Pull request by darknight7**
Adding ETA (countdown to full sync) functionality, I did it for myself and I submit it for review in case you want to integrate the functionality in the official scripts. Also made a few consistency changes here and there.

### CODE REVIEW

**Comment by h4x3rotab** [comment]
@hauni97 Could you take a look?

**Review by hauni97 — DISMISSED** [review]
lgtm

**Comment by h4x3rotab** [comment]
Is it still valuable to merge? @hauni97

**Comment by hauni97** [comment]
> Is it still valuable to merge? @hauni97

Currently not. Let me know if I can close this PR @h4x3rotab for now.

**Pull request closed without merging**
