### PR TITLE
GUI single install & Compatibility improvements in Scripts

### PR DESCRIPTION
**Pull request by hauni97**
This adds compatibility for Ubuntu 21.10 & installs the miner.
Furthermore there is now a GUI installation for the miner, that allows an installation from a single command.

### CODE REVIEW

**Comment by hauni97** [comment]
Please thoroughly test it prior to merging this to main. It was successfully tested on Ubuntu 21.10 with Hetzner and Vultr.

**Comment by hauni97** [comment]
This is the branch from which the GUI script takes its source code from. Do not delete this branch after merging yet. 
The [beta-gui](https://github.com/Phala-Network/solo-mining-scripts/tree/beta-gui) branch (a duplicate of this branch) was created as requested by @h4x3rotab and is intended to be used for early adopters prior to merging this branch to main as of now.

**Comment by hauni97** [comment]
TODO: Best practices auto start + troubleshoot according to: [docker docs](https://docs.docker.com/compose/compose-file/compose-file-v3/), thx @h4x3rotab for this.

**Comment by h4x3rotab** [comment]
Assigned to our enginner to test it out

**Comment by hauni97** [comment]
# Biggest Improvements for Miners using this Script

* [x] The mining installation script now has a GUI (2 min full installation)
     * [x] A single command is now required to install the miner, this substitutes 7-8 commands
     * [x] The GUI has successfully been tested on Ubuntu 18.04 & Ubuntu 21.10 @skysummerice feel free to test it again
* [x] The mining script now works on Ubuntu 21.10 & higher Kernel Versions with a native DCAP driver. 
* [x] Docker installation Error is fixed: https://github.com/Phala-Network/solo-mining-scripts/pull/38/commits/60bc5ae262aaa096a42d80ea606ecdba6415c3c8
* [x] A common bug, that isgx did not install automatically when the DCAP driver installation failed is fixed as well: https://github.com/Phala-Network/solo-mining-scripts/pull/38/commits/a34802751b7650c8fbbb1f8428810ff7fe262605
* [x] Many other small changes & fixes

# TODO

- [ ] Final tests @skysummerice 
- [ ] Future considerations: docker containers autostart best practices: https://github.com/Phala-Network/solo-mining-scripts/pull/38#issuecomment-996544456

**Pull request closed without merging**
